name: crome-logic

channels:
  - default
  - conda-forge

dependencies:
  - python=3.10
  - pygraphviz
  - spot
  - pre-commit
  - matplotlib
  - poetry
  - gcc
  - pip
  - pip:
      - pyeda
      - aenum
      - treelib
      - docker
      - bloom-filter
      - dill
